name = "GlobalAnalysis"
uuid = "0697fe54-52cc-445b-8059-c053b5e91f02"
authors = ["Michael Sachs"]
version = "0.1.0"

[compat]
julia = "1.5.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
